application:
  name: QXCMP
  short-name: test
spring:
  profiles:
    active: qxcmp
  datasource:
    url: jdbc:mysql://localhost:3306/qxcmp?useSSL=false&characterEncoding=utf8
    username: qxcmp
    password: qxcmp
    driverClassName: com.mysql.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1
    platform: mysql
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect